name = "atuin"
description = "Magical shell history"
homepage = "https://atuin.sh"
alternatives = [ "mcfly", "hishtory" ]
version = "18.4.0"
updated = "2024-12-27"
package-url = "https://github.com/atuinsh/atuin/releases/download/v{{version}}/atuin-x86_64-unknown-linux-musl.tar.gz"
post-commands = [ "{{vars.bin-path}}/atuin gen-completions --shell {{vars.shell-type}} --out-dir {{vars.complete-path}}"]

[extract]
strip = 1

[[extract.files]]
source = "atuin"
target = "{{vars.bin-path}}/atuin"
mode = "0755"
