name = "cppfront"
description = "A personal experimental C++ Syntax 2 -> Syntax 1 compiler -- NOT FOR COMMERICAL USE!"
homepage = "https://github.com/hsutter/cppfront"
alternatives = []
version = "0.7.4"
updated = "2024-08-27"
package-url = ""

# NOTE: you might want this here too: https://github.com/modern-cmake/cppfront

#
# build configuration
#

[build]
package-url = "https://github.com/hsutter/cppfront/archive/refs/tags/v{{version}}.tar.gz"
version-pattern = "v\\d+\\.\\d+\\.\\d+$"

[[build.script]]
name = "build_cppfront.sh"
content = [
    "set -e",
    "tar xzf v{{version}}.tar.gz --strip-components=1",
    "g++ source/cppfront.cpp -std=c++20 -o cppfront",
    "tar cJf cppfront-{{version}}.linux.x86_64.tar.xz cppfront"
]

[[build.step]]
command = ["xcc", "el7", "sh", "build_cppfront.sh", "el7"]

[[build.publish]]
repository-name = "packages"
repository-path = "cppfront"
files = ["cppfront-{{version}}.linux.x86_64.tar.xz"]
