name = "duf"
description = "Disk Usage/Free Utility - a better 'df' alternative"
homepage = "https://github.com/muesli/duf"
alternatives = [ "df",]
version = "0.9.1"
updated = "2025-09-09"
package-url = "https://github.com/muesli/duf/releases/download/v{{version}}/duf_{{version}}_linux_x86_64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "duf"
target = "{{vars.bin-path}}/duf"
mode = "0755"
