name = "fd"
description = "A simple, fast and user-friendly alternative to 'find'"
homepage = "https://github.com/sharkdp/fd"
alternatives = [ "find",]
version = "10.2.0"
updated = ""
package-url = "https://github.com/sharkdp/fd/releases/download/v{{version}}/fd-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1
prefix = "{{vars.bin-path}}"
[[extract.files]]
source = "fd"
target = "{{vars.bin-path}}/fd"
mode = "0755"

[[extract.files]]
source = "autocomplete/fd.{{vars.shell-type}}"
target = "{{vars.complete-path}}/_fd"

