name = "gdu"
description = "Fast disk usage analyzer with console interface written in Go"
homepage = "https://github.com/dundee/gdu"
alternatives = [ "du", "dust", "ncdu",]
version = "5.31.0"
updated = "2025-06-06"
package-url = "https://github.com/dundee/gdu/releases/download/v{{version}}/gdu_linux_amd64_static.tgz"

[extract]
strip = 0

[[extract.files]]
source = "gdu_linux_amd64_static"
target = "{{vars.bin-path}}/gdu"
mode = "0755"
