name = "git-cryp"
description = "Transparent file encryption in git"
homepage = "https://www.agwa.name/projects/git-crypt"
alternatives = []
version = "0.8.0"
updated = "2025-09-24"
package-url = "https://github.com/AGWA/git-crypt/releases/download/{{version}}/git-crypt-{{version}}-linux-x86_64"

[extract]
strip = 0

[[extract.files]]
source = "git-crypt-{{version}}-linux-x86_64"
target = "{{vars.bin-path}}/git-crypt"
mode = "0755"
