name = "glow"
description = "Render markdown on the CLI, with pizzazz!"
homepage = "https://github.com/charmbracelet/glow"
alternatives = []
version = "2.1.1"
updated = "2025-05-30"
package-url = "https://github.com/charmbracelet/glow/releases/download/v{{version}}/glow_Linux_x86_64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "glow"
target = "{{vars.bin-path}}/glow"
mode = "0755"

[[extract.files]]
source = "completions/glow.{{vars.shell-type}}"
target = "{{vars.complete-path}}/_glow"
