name = "jid"
description = "json incremental digger"
homepage = "https://github.com/simeji/jid"
alternatives = [ ]
version = "1.1.1"
updated = "2026-04-01"
package-url = "https://github.com/simeji/jid/releases/download/v{{version}}/jid_linux_amd64.zip"

[extract]
strip = 0

[[extract.files]]
source = "jid"
target = "{{vars.bin-path}}/jid"
mode = "0755"
