name = "mcfly"
description = "Fly through your shell history. Great Scott!"
homepage = "https://github.com/cantino/mcfly"
alternatives = [ "atuin", "hishtory",]
version = "0.9.2"
updated = "2024-08-12"
package-url = "https://github.com/cantino/mcfly/releases/download/v{{version}}/mcfly-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "mcfly"
target = "{{vars.bin-path}}/mcfly"
mode = "0755"
