name = "sonarscanner"
description = "The SonarScanner CLI is the scanner to use when there is no specific scanner for your build system."
homepage = "https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/"
alternatives = []
version = "7.0.0.4796"
updated = "2025-01-20"
package-url = ""
query-url = "https://github.com/SonarSource/sonar-scanner-cli/archive/refs/tags/{{version}}.zip"
version-pattern = "\\d+\\.\\d+\\.\\d+\\.\\d+"

#
# build configuration
#

[build]
package-url = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{version}}.zip"

[[build.publish]]
repository-name = "packages"
repository-path = "sonarscanner"
files = ["sonar-scanner-cli-{{version}}.zip"]
