name = "teller"
description = "Cloud native secrets management for developers - never leave your command line for secrets."
homepage = "https://github.com/tellerops/teller"
alternatives = []
version = "2.0.7"
updated = "2024-05-20"
package-url = "https://github.com/tellerops/teller/releases/download/v{{version}}/teller-x86_64-linux.tar.xz"

[extract]
strip = 1
prefix = "{{vars.bin-path}}"
