name = "up"
description = "Ultimate Plumber is a tool for writing Linux pipes with instant live preview"
homepage = "https://github.com/akavel/up"
alternatives = []
version = "0.4"
updated = ""
package-url = "https://github.com/akavel/up/releases/download/v{{version}}/up"
version-pattern = "^v\\d+\\.\\d+(\\.\\d+)?$$"

[extract]
strip = 0
[[extract.files]]
source = "up"
target = "{{vars.bin-path}}/up"
mode = "0755"
