name = "zsh-completions"
description = "Additional completion definitions for Zsh."
homepage = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/{{version}}.tar.gz"
alternatives = []
version = "0.36.0"
updated = "2026-03-09"
package-url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/{{version}}.tar.gz"

[extract]
strip = 1
prefix = "{{vars.zsh-plugin-path}}/zsh-completions"
