name = "zsh-fzf-tab"
description = "Replace zsh's default completion selection menu with fzf!"
homepage = "https://github.com/Aloxaf/fzf-tab/archive/refs/tags/v{{version}}.tar.gz"
alternatives = []
version = "1.1.2"
updated = "2024-05-10"
package-url = "https://github.com/Aloxaf/fzf-tab/archive/refs/tags/v{{version}}.tar.gz"

[extract]
strip = 1
prefix = "{{vars.zsh-plugin-path}}/fzf-tab"
